version: '3'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_group_dreamers_development
      MYSQL_USER: juliomoquenco
      MYSQL_PASSWORD: 12345dev#
    ports:
      - "3307:3306"

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0'"
    volumes:
      - ".:/test_group_dreamers"
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 3307

      DATABASE_USER: root
      DATABASE_PASSWORD: root

      DATABASE_DEVELOPMENT_NAME: test_group_dreamers_development
      DATABASE_TEST_NAME: test_group_dreamers_test
