---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/tourist_spot":
    parameters:
    - name: name
      in: query
      description: name
      required: true
      schema:
        type: string
    - name: lang
      in: query
      description: lang
      schema:
        type: string
    get:
      summary: list tourist_spots
      responses:
        '200':
          description: successful
servers:
- url: http://localhost:3000
  variables:
    defaultHost:
      default: localhost
