---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/tourist_spot":
    get:
      summary: list tourist_spots
      responses:
        '200':
          description: successful
  "/tourist_spot/result":
    get:
      summary: result tourist_spot
      responses:
        '200':
          description: successful
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
